### ISSUE TITLE
big bee data reporting

### ISSUE THREAD

**Issue by jhpoelen** [Big-Bee-Network/issues-observations-and-questions#4]
hey @seltmann - 

Some time ago, you asked how to generate data reports like those used in Terrestrial Parasite Tracker.

Please see:

https://github.com/parasitetracker/tpt-reporting 

for an updated readme with examples and links to existing reports.

Let me know if you need additional pointers / help to generate the first (!) Big Bee data review report.

Hope this helps. . .

**Comment by seltmann** [comment]
@jhpoelen great! Thanks for bringing this up again. I do not remember the steps for creating the review files. Can you point me in the right direction?

**Comment by jhpoelen** [comment]
Great to see Seltmann, Katja C., & Poelen, Jorrit H. (2021). Big Bee indexed biotic interactions and review summary (0.1) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.5722445 !

Nice!

Just wondering - is there a specific reason you are using an old version of Elton (v0.9.6) instead of the most recent one (v0.12.2) ?

**Comment by seltmann** [comment]
@jhpoelen well, I used the older version of elton because I missed the step to update before. I  added that to the instructions. https://github.com/Big-Bee-Network/bigbee-globi-reporting/blob/main/README.md

Did you notice that I also included a review file that is just bee data? Probably a better way to incorporate this into the Big Bee review but includes indexed_interactions_bees.tsv.zip that is all indexed bee data and the number of indexed bee interactions per collection.

**Comment by jhpoelen** [comment]
@seltmann yes! I did notice your bee interactions. Very cool to see how you are making the reports suit the big bee project. How did you select the bee names?

**Comment by seltmann** [comment]
@ grep by family 
https://github.com/Big-Bee-Network/bigbee-globi-reporting/blob/main/Globi_bee_data.sh

**Comment by jhpoelen** [comment]
Neat! 

Did you consider using Nomer + discoverlife ?

**Comment by seltmann** [comment]
@jhpoelen I did consider it, but it did not make sense to use Nomer + discoverlife as many of the bee records are not determined to species. By selecting only by family  I was able to get more records. Nomer will be very useful for another report to asking how many records per species
